### ISSUE TITLE
Styling inconsistency

### ISSUE THREAD

**Issue by Tereseus** [bongio79/colmar#1]
"Our guest lecture & Fisma: design and prototype" have a different background color compared to the other elements around them. Was that intentional? It would make more sense for their background to be white.

**Comment by bongio79** [comment]
Oh, that's because it was like that in the Document Spec too:
https://s3.amazonaws.com/codecademy-content/courses/freelance-1/capstone-2/colmar-academy-spec.png

**Comment by Tereseus** [comment]
Oh ok, the solution I have doesn't have it like that. Thanks for showing that to me.

**Comment by bongio79** [comment]
You're welcome. And thanks for the review.
